class PySQLScribeError(Exception): ...


class InvalidNodeError(PySQLScribeError): ...


class DialectValidationError(PySQLScribeError): ...


class InvalidColumnNameError(PySQLScribeError): ...


class InvalidColumnsError(PySQLScribeError): ...


class InvalidTableNameError(PySQLScribeError): ...


class InvalidSchemaNameError(PySQLScribeError): ...


class InvalidJoinError(PySQLScribeError): ...


class DuplicateCTENameError(PySQLScribeError): ...


class EmptyCTEError(PySQLScribeError): ...


class InvalidPathError(PySQLScribeError):
    """Custom exception for cases where a path not containing '.sql' files is provided"""
