class PySQLScribeError(Exception): ...


class InvalidNodeError(PySQLScribeError): ...


class DialectValidationError(PySQLScribeError): ...


class InvalidColumnNameError(PySQLScribeError): ...


class InvalidColumnsError(PySQLScribeError): ...


class InvalidTableNameError(PySQLScribeError): ...


class InvalidSchemaNameError(PySQLScribeError): ...


class InvalidJoinError(PySQLScribeError): ...


class DuplicateCTENameError(PySQLScribeError): ...


class EmptyCTEError(PySQLScribeError): ...
